# Generated by Django 2.2.13 on 2020-07-04 12:55

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ong',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('cnpj', models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(14)])),
                ('description', models.TextField(null=True)),
                ('cep', models.CharField(max_length=10)),
                ('state', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=100, null=True)),
                ('address', models.CharField(max_length=1024)),
                ('number', models.IntegerField()),
                ('complement', models.CharField(max_length=1024, null=True)),
                ('link', models.CharField(max_length=100, null=True)),
                ('date_register', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'ongs',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'tag',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=10, unique=True)),
                ('key', models.CharField(max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'user_project',
            },
        ),
        migrations.CreateModel(
            name='NeedProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('amount', models.IntegerField(default=1)),
                ('description', models.TextField(null=True)),
                ('active', models.BooleanField(default=True)),
                ('date_register', models.DateTimeField(auto_now_add=True)),
                ('ong', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Ong')),
                ('tags', models.ManyToManyField(to='api.Tag')),
            ],
            options={
                'db_table': 'needs_product',
            },
        ),
        migrations.CreateModel(
            name='NeedBill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(null=True)),
                ('expiration', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('active', models.BooleanField(default=True)),
                ('date_register', models.DateTimeField(auto_now_add=True)),
                ('ong', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Ong')),
                ('tags', models.ManyToManyField(to='api.Tag')),
            ],
            options={
                'db_table': 'needs_bill',
            },
        ),
    ]
