# Generated by Django 2.2.13 on 2020-07-05 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200705_1308'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contributionproducts',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='needbill',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='needproduct',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='needvoluntary',
            name='tags',
        ),
        migrations.AlterField(
            model_name='contributionproducts',
            name='grantor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Grantor'),
        ),
        migrations.AlterField(
            model_name='contributionproducts',
            name='need',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.NeedProduct'),
        ),
        migrations.RemoveField(
            model_name='ong',
            name='cause',
        ),
        migrations.AddField(
            model_name='ong',
            name='cause',
            field=models.ManyToManyField(to='api.Tag'),
        ),
    ]
