# Generated by Django 2.2.13 on 2020-07-05 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200705_1931'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ong',
            name='cause',
        ),
        migrations.AddField(
            model_name='ong',
            name='cause',
            field=models.CharField(max_length=1024, null=True),
        ),
    ]
